apiVersion: v1
kind: Service
metadata:
  name: fenzhodraft
  namespace: default
  labels:
    kubernetes.azure.com/generator: draft
spec:
  type: LoadBalancer
  selector:
    app: fenzhodraft
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80